// <auto-generated />
using System;
using BitcoinCurrentPrice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitcoinCurrentPrice.Migrations
{
    [DbContext(typeof(BitcoinContext))]
    [Migration("20191205151545_AddedAllTable")]
    partial class AddedAllTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitcoinCurrentPrice.Models.Bpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EURId")
                        .HasColumnType("int");

                    b.Property<int>("GBPId")
                        .HasColumnType("int");

                    b.Property<int>("USDId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EURId");

                    b.HasIndex("GBPId");

                    b.HasIndex("USDId");

                    b.ToTable("Bpis");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.EUR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rate_float")
                        .HasColumnType("float");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EURs");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.GBP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rate_float")
                        .HasColumnType("float");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GBPs");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.RootObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BpiId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<string>("chartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disclaimer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BpiId");

                    b.HasIndex("TimeId");

                    b.ToTable("RootObjects");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updatedISO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateduk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.USD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rate_float")
                        .HasColumnType("float");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USDs");
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.Bpi", b =>
                {
                    b.HasOne("BitcoinCurrentPrice.Models.EUR", "EUR")
                        .WithMany("Bpis")
                        .HasForeignKey("EURId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitcoinCurrentPrice.Models.GBP", "GBP")
                        .WithMany("Bpis")
                        .HasForeignKey("GBPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitcoinCurrentPrice.Models.USD", "USD")
                        .WithMany("Bpis")
                        .HasForeignKey("USDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitcoinCurrentPrice.Models.RootObject", b =>
                {
                    b.HasOne("BitcoinCurrentPrice.Models.Bpi", "Bpi")
                        .WithMany("RootObjects")
                        .HasForeignKey("BpiId");

                    b.HasOne("BitcoinCurrentPrice.Models.Time", "Time")
                        .WithMany("RootObjects")
                        .HasForeignKey("TimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
